# Generated by Django 4.2.5 on 2023-10-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
