# Generated by Django 4.2.5 on 2023-10-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='age',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='mobile',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
